language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install python-coveralls
  - pip install -r requirements.txt
  - cp sublimall/local_settings_example.py sublimall/local_settings.py
script:
  - python manage.py test
after_success:
  - coveralls